os: linux
dist: xenial

language: php

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.0
 - 7.1
 - 7.2
 - 7.3

env:
 global:
  - DB=mysqli
 jobs:
  - MOODLE_BRANCH=master
  - MOODLE_BRANCH=MOODLE_39_STABLE
  - MOODLE_BRANCH=MOODLE_38_STABLE
  - MOODLE_BRANCH=MOODLE_37_STABLE
  - MOODLE_BRANCH=MOODLE_36_STABLE
  - MOODLE_BRANCH=MOODLE_35_STABLE
  - MOODLE_BRANCH=MOODLE_34_STABLE

jobs:
  exclude:
  - php: 7.0
    env: MOODLE_BRANCH=master 
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_39_STABLE 
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_38_STABLE 
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_37_STABLE 
  - php: 7.1
    env: MOODLE_BRANCH=master 
  - php: 7.3
    env: MOODLE_BRANCH=MOODLE_35_STABLE 
  - php: 7.3
    env: MOODLE_BRANCH=MOODLE_34_STABLE 

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0
  - nvm use 14.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
